import { useCallback, useEffect, useRef, useState } from 'react'
import { ShieldCheck, Camera, Bell, LayoutDashboard, Settings, LogOut, X, Plus, Check, RefreshCw, Activity, BarChart3 } from 'lucide-react'
import { ru, kk, type Key } from './i18n'
import './App.css'

type Event = {id:string;camera_id:string;camera_name:string;type:Key;severity:string;detected_at:string;status:'new'|'confirmed'|'dismissed';snapshot_url:string;confidence:number;detection_mode:Key;telegram_sent:boolean;feedback_note?:string}
type Zone = {id:string;name:string;kind:string;polygon?:number[][]}
type Source = {id:string;name:string;location:string;url:string;source_type:string;enabled:boolean;fps_limit:number;zones:Zone[]}
type Cam = {id:string;name:string;location:string;status:string;source_type:string;ai_status:string}
type Detection = {status:Key;category:Key;person_count:number}
type Config = {absence_threshold_minutes:number;shelf_dwell_seconds:number;confidence_threshold:number;fall_hold_seconds:number;fight_motion_threshold:number}
const API = (import.meta.env.VITE_API_URL || '').trim().replace(/\/+$/, '')
const FREE_DEMO = import.meta.env.VITE_FREE_DEMO === '1'
const categories:Key[] = ['normal','suspicious','fight','fall','danger']
function App(){
 const [lang,setLang]=useState<'ru'|'kk'>(()=>localStorage.getItem('safetyLanguage')==='kk'?'kk':'ru')
 const t=useCallback((key:Key)=> (lang==='kk'?kk:ru)[key] || key,[lang])
 const [token,setToken]=useState(localStorage.getItem('AegisAuthToken')||'')
 const [role,setRole]=useState('operator')
 const [tab,setTab]=useState<Key>('overview')
 const [events,setEvents]=useState<Event[]>([]),[cameras,setCameras]=useState<Cam[]>([]),[sources,setSources]=useState<Source[]>([])
 const [detections,setDetections]=useState<Record<string,Detection>>({}),[config,setConfig]=useState<Config|null>(null)
 const [telegram,setTelegram]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [selected,setSelected]=useState<Event|null>(null),[note,setNote]=useState(''),[form,setForm]=useState<Source|null>(null)
 const [poly,setPoly]=useState(''),[kind,setKind]=useState('work_area')
 const [filter,setFilter]=useState({camera:'',type:'',status:'',from:'',to:''})
 const [visibleCount,setVisibleCount]=useState(100)
 const [testCamera,setTestCamera]=useState(''),[testType,setTestType]=useState<Key>('fall')
 const seen=useRef<Set<string>|null>(null)
 const request=useCallback(async <T,>(path:string, method='GET',body?:unknown):Promise<T>=>{
  const result=await fetch(API+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:body===undefined?undefined:JSON.stringify(body)})
  if(!result.ok){if(result.status===401 && !path.includes('/auth/login')){localStorage.removeItem('AegisAuthToken');setToken('')}throw new Error(result.status===401?t('unauthorized'):t('error'))}
  return result.json()
 },[token,t])
 const load=useCallback(async()=>{
  try{
   const [ev,cam,src,settings,overview,user]=await Promise.all([request<Event[]>('/api/events'),request<Cam[]>('/api/cameras'),request<Source[]>('/api/camera-sources'),request<Config>('/api/settings'),request<{telegram_configured:boolean}>('/api/overview'),request<{role:string}>('/api/auth/me')])
   if(seen.current && ev.some(e=>!seen.current!.has(e.id)&&e.status==='new'&&e.type!=='normal'))setNotice(t('alert'))
   seen.current=new Set(ev.map(e=>e.id));setEvents(ev);setCameras(cam);setSources(src);setConfig(old=>old||settings);setTelegram(overview.telegram_configured);setRole(user.role)
   const ds=await Promise.all(cam.map(async c=>[c.id,await request<Detection>(`/api/cameras/${c.id}/detections`)] as const));setDetections(Object.fromEntries(ds));setError('')
  }catch(e){setError((e as Error).message)}
 },[request,t])
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('safetyLanguage',lang)},[lang])
 useEffect(()=>{if(!token)return;void load();const id=setInterval(()=>void load(),5000);return()=>clearInterval(id)},[load,token])
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id)},[notice])
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function feedback(status:'confirmed'|'dismissed'){
  if(!selected)return
  await action(async()=>{const ev=await request<Event>(`/api/events/${selected.id}/feedback`,'POST',{status,note,reviewed_by:'operator'});setSelected(ev);setEvents(old=>old.map(e=>e.id===ev.id?ev:e));setNotice(t('saved'))})
 }
 function editCamera(source?:Source){setForm(source||{id:crypto.randomUUID(),name:'',location:'',url:'',source_type:'rtsp',enabled:true,fps_limit:8,zones:[]});setKind(source?.zones[0]?.kind||'work_area');setPoly(source?.zones[0]?.polygon?JSON.stringify(source.zones[0].polygon):'')}
 async function saveCamera(){
  if(!form)return
  await action(async()=>{
   let polygon:number[][]|undefined
   try {polygon=poly.trim()?JSON.parse(poly):undefined;if((kind==='restricted'&&!polygon)||(polygon&&(!Array.isArray(polygon)||polygon.length<3||polygon.some(p=>!Array.isArray(p)||p.length!==2||p.some(n=>typeof n!=='number'||n<0||n>1)))))throw new Error()}catch{throw new Error(t('invalidZone'))}
   const zone={id:form.zones[0]?.id||`zone-${form.id}`,name:t(kind as Key),kind,polygon}
   await request('/api/camera-sources','POST',{...form,zones:[zone,...form.zones.slice(1)]});setForm(null);await load();setNotice(t('saved'))
  })
 }
 const language=<div className="languages"><button className={lang==='ru'?'active':''} onClick={()=>setLang('ru')}>RU</button><button className={lang==='kk'?'active':''} onClick={()=>setLang('kk')}>ҚАЗ</button></div>
 const privileged=role==='admin'||role==='manager'
 const filtered=events.filter(e=>(!filter.camera||e.camera_id===filter.camera)&&(!filter.type||e.type===filter.type)&&(!filter.status||e.status===filter.status)&&(!filter.from||new Date(e.detected_at)>=new Date(filter.from+'T00:00:00'))&&(!filter.to||new Date(e.detected_at)<=new Date(filter.to+'T23:59:59.999')))
 const date=(value:string)=>new Date(value).toLocaleString(lang==='kk'?'kk-KZ':'ru-RU')
 const metrics=[{label:'online',value:cameras.filter(c=>c.status==='online').length+'/'+cameras.length},{label:'open',value:events.filter(e=>e.status==='new'&&e.type!=='normal').length},{label:'confirmed',value:events.filter(e=>e.status==='confirmed').length},{label:'dismissed',value:events.filter(e=>e.status==='dismissed').length}] as const
 if(!token)return <div className="login"><div className="login-panel"><div className="login-top"><ShieldCheck size={36}/>{language}</div><h1>AI Camera Safety</h1><p>{t('subtitle')}</p>{FREE_DEMO&&<p className="hint">{t('freeDemo')}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const result=await request<{access_token:string;user:{role:string}}>('/api/auth/login','POST',{username:f.get('username'),password:f.get('password')});localStorage.setItem('AegisAuthToken',result.access_token);setRole(result.user.role);seen.current=null;setToken(result.access_token)})}}><label>{t('username')}<input name="username" autoComplete="username" required/></label><label>{t('password')}<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{t('login')}</button></form><small>{t('platform')}</small></div></div>
 return <div className="shell"><aside><div className="brand"><ShieldCheck/><div>AI Camera Safety<small>{t('subtitle')}</small></div></div><nav>{([['overview',LayoutDashboard],['events',Bell],['cameras',Camera],['analytics',BarChart3],['settings',Settings]] as const).map(([key,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/>{t(key)}</button>)}</nav><div className="aside-bottom"><span className="pill">MVP</span><p>{t('platform')}</p></div></aside><main>{FREE_DEMO&&<p className="panel" role="status">{t('freeDemo')}</p>}<header><div><span className="eyebrow">AI CAMERA SAFETY</span><h1>{t(tab)}</h1></div><div className="header-actions">{language}<button aria-label={t('refresh')} onClick={()=>void load()}><RefreshCw size={18}/></button><button aria-label={t('logout')} onClick={()=>{localStorage.removeItem('AegisAuthToken');setToken('');setConfig(null);seen.current=null}}><LogOut size={18}/></button></div></header>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="toast" role="status"><Bell size={18}/>{notice}</div>}
 {(tab==='overview'||tab==='analytics')&&<div className="metrics">{metrics.map(m=><section key={m.label}><span>{t(m.label)}</span><strong>{m.value}</strong><Activity size={18}/></section>)}</div>}
 {(tab==='overview'||tab==='cameras')&&<><div className="section-title"><h2>{t('live')}</h2>{privileged&&<button className="primary" onClick={()=>editCamera()}><Plus size={16}/>{t('addCamera')}</button>}</div><div className="camera-grid">{cameras.map(c=><article className="camera-card" key={c.id}><div className="feed"><AuthImage token={token} src={`/api/cameras/${c.id}/frame_analyzed.jpg`} alt={c.name} fallback={t('noFrame')} live/><span className={'feed-status '+(c.status==='online'?'ok':'')}>{t(c.status==='online'?'online':'offline')}</span><span className={'category '+(detections[c.id]?.category||'unknown')}>{t(detections[c.id]?.category||'unknown')}</span></div><div className="camera-info"><div><h3>{c.name}</h3><p>{c.location}</p></div><button onClick={()=>void action(async()=>{const result=await request<{reason:Key}>(`/api/camera-sources/${c.id}/readiness`);setNotice(t(result.reason))})}>{t('probe')}</button>{privileged&&<button onClick={()=>editCamera(sources.find(s=>s.id===c.id))}>{t('edit')}</button>}</div><div className="camera-footer"><span>{t(detections[c.id]?.status||'warming_up')}</span><span>{FREE_DEMO?t('viewerOnly'):c.source_type==='retail_scene'?t('demo'):'YOLO + OpenCV'}</span></div></article>)}</div>{!cameras.length&&<p>{t('noCameras')}</p>}<p className="hint">{t('limitations')}</p></>}
 {(tab==='overview'||tab==='events')&&<><div className="section-title"><h2>{t('events')}</h2><span className="pill">{filtered.length}</span></div><div className="filters"><label>{t('camera')}<select value={filter.camera} onChange={e=>setFilter({...filter,camera:e.target.value})}><option value="">{t('all')}</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{t('category')}<select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})}><option value="">{t('all')}</option>{categories.map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label>{t('status')}<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">{t('all')}</option>{(['new','confirmed','dismissed'] as const).map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label>{t('from')}<input type="date" value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>{t('to')}<input type="date" value={filter.to} onChange={e=>setFilter({...filter,to:e.target.value})}/></label></div><div className="event-list">{filtered.slice(0,visibleCount).map(ev=><button className="event-row" key={ev.id} onClick={()=>{setSelected(ev);setNote(ev.feedback_note||'')}}><span className={'dot '+ev.type}/><div><strong>{t(ev.type)}</strong><small>{ev.camera_name} · {date(ev.detected_at)}</small></div><span className="mode">{t(ev.detection_mode)}</span><span className={'pill '+ev.status}>{t(ev.status)}</span></button>)}{filtered.length>visibleCount&&<button className="event-row" onClick={()=>setVisibleCount(n=>n+100)}>{t('more')}</button>}{!filtered.length&&<div className="empty"><ShieldCheck size={36}/><h3>{t('empty')}</h3><p>{t('emptyHint')}</p></div>}</div></>}
 {tab==='analytics'&&<section className="panel"><h2>{t('category')}</h2>{categories.map(k=>{const count=events.filter(e=>e.type===k).length;return <div className="bar-row" key={k}><span>{t(k)}</span><div className="bar"><div className={k} style={{width:`${count/Math.max(1,events.length)*100}%`}}/></div><strong>{count}</strong></div>})}<p className="hint">{t('total')}: {events.length}</p></section>}
 {tab==='settings'&&<div className="settings-grid"><section className="panel"><h2>{t('thresholds')}</h2>{config&&<form onSubmit={e=>{e.preventDefault();void action(async()=>{await request('/api/settings','PUT',config);setNotice(t('saved'))})}}>{([['shelf_dwell_seconds','dwell',5,600,1],['confidence_threshold','threshold',0.1,0.99,0.01],['fall_hold_seconds','fallHold',0.5,10,0.1],['fight_motion_threshold','motion',0.1,5,0.1]] as const).map(([key,label,min,max,step])=><label key={key}>{t(label)}<input type="number" min={min} max={max} step={step} value={config[key]} disabled={!privileged} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}/></label>)}{privileged&&<button className="primary" disabled={busy}>{t('save')}</button>}</form>}<p className="hint">{t('limitations')}</p></section><section className="panel"><h2>{t('notifications')}</h2><p>{t('telegram')} <span className="pill">{t(telegram?'configured':'notConfigured')}</span></p><p className="hint">{t('telegramHint')}</p><h2>{t('test')}</h2><p className="hint">{t('testHint')}</p>{privileged&&<><label>{t('camera')}<select value={testCamera||cameras[0]?.id||''} onChange={e=>setTestCamera(e.target.value)}>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{t('category')}<select value={testType} onChange={e=>setTestType(e.target.value as Key)}>{categories.map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><button disabled={busy||!cameras.length} onClick={()=>void action(async()=>{await request('/api/events/simulate','POST',{camera_id:testCamera||cameras[0].id,event_type:testType});await load();setNotice(t('saved'))})}>{t('createTest')}</button></>}</section></div>}
 </main>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label={t('detail')} className="modal" onClick={e=>e.stopPropagation()}><div className="section-title"><h2>{t(selected.type)}</h2><button aria-label={t('close')} onClick={()=>setSelected(null)}><X/></button></div><div className="event-frame"><AuthImage token={token} src={selected.snapshot_url} alt={t(selected.type)} fallback={t('noFrame')}/></div><div className="detail-meta"><span>{selected.camera_name}</span><span>{date(selected.detected_at)}</span><span>{t(selected.detection_mode)}</span><span>{t(selected.status)}</span></div><p className="hint">{t('confidence')}: {Math.round(selected.confidence*100)}%</p><p>{t('candidate')}</p><label>{t('note')}<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button className="primary" disabled={busy} onClick={()=>void feedback('confirmed')}><Check size={18}/>{t('confirm')}</button><button disabled={busy} onClick={()=>void feedback('dismissed')}><X size={18}/>{t('falseAlarm')}</button></div></section></div>}
 {form&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={t('addCamera')}><div className="section-title"><h2>{t('addCamera')}</h2><button onClick={()=>setForm(null)} aria-label={t('close')}><X/></button></div><form onSubmit={e=>{e.preventDefault();void saveCamera()}}><label>{t('name')}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t('location')}<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>{t('source')}<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})}>{(['rtsp','hls','demo_video','jpeg_snapshot','live_mjpeg','retail_scene'] as const).map(k=><option key={k} value={k}>{k==='demo_video'?t('video'):t(k)}</option>)}</select></label><label>{t('url')}<input required value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="rtsp://192.168.1.10:554/stream"/></label><label className="checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>{t('enabled')}</label><label>{t('zoneKind')}<select value={kind} onChange={e=>setKind(e.target.value)}>{(['work_area','shelf','stock','restricted'] as const).map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label>{t('polygon')}<textarea value={poly} onChange={e=>setPoly(e.target.value)} placeholder="[[0.1,0.1],[0.9,0.1],[0.9,0.9],[0.1,0.9]]"/></label><p className="hint">{t('polygonHint')}</p>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{t('save')}</button></form></section></div>}
 </div>
}
function AuthImage({src,token,alt,fallback,live=false}:{src:string;token:string;alt:string;fallback:string;live?:boolean}){
 const [url,setUrl]=useState('')
 useEffect(()=>{
  let active=true,objectUrl='';const controller=new AbortController()
  const load=async()=>{try{const response=await fetch(API+src,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});if(!response.ok){if(active)setUrl('');return}const blob=await response.blob();if(!active)return;const next=URL.createObjectURL(blob);setUrl(next);if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=next}catch{if(active)setUrl('')}}
  void load();const interval=live?setInterval(()=>void load(),2000):undefined
  return()=>{active=false;controller.abort();clearInterval(interval);if(objectUrl)URL.revokeObjectURL(objectUrl)}
 },[src,token,live])
 return url?<img src={url} alt={alt}/>:<div className="no-frame"><Camera size={32}/><span>{fallback}</span></div>
}
export default App
